### ISSUE TITLE
Request for New Release Including WriteAsSVG Function

### ISSUE THREAD

**Issue by ValentinKolb** [piglig/go-qr#89]
Hi go-qr Team,

First off, thank you for your amazing work on this project. I've been exploring the source code and noticed the `WriteAsSVG` function, which would be incredibly useful for my current project.

Could you please let me know if there are any plans for a new release that includes this function? Having it officially available would greatly benefit my work.

Thanks for considering my request. I appreciate all the effort you put into go-qr.

Best regards,
Valentin

**Comment by piglig** [comment]
Thank you for your interest in this project! The WriteAsSVG function will be released in the next few days.

**Comment by ValentinKolb** [comment]
Thank you very much 😃
