### ISSUE TITLE
Didn't work when supplying a wifi connection string - zsh killed the session due to timeout

### ISSUE THREAD

**Issue by ilium007** [piglig/go-qr#93]
Tried using the following:

`generator -content "WIFI:S:mYwIfI;T:WPA;P:secret_passwordt;H:false;;" -svg-optimized /Users/me/support/wifi.svg`

Worked when using a simple string.

**Comment by ilium007** [comment]
The wifi string worked when NOT adding `-svg-optimized /Users/me/support/wifi.svg`

**Comment by ilium007** [comment]
Just using `-svg` works as well. `-svg-optimized `does not work at all.

**Comment by piglig** [comment]
Thanks for your feedback, I have solved this bug now. You can install the latest version of **generator**. 
![企业微信截图_20241212142922](https://github.com/user-attachments/assets/1bcf1fe2-903a-4dc0-a0c8-3bd897bccb19)

**Comment by ilium007** [comment]
That works - thanks!
